[package]
name = "bundlr-sdk"
description = "Bundlr Network Rust sdk"
homepage = "https://bundlr.network"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Bundlr-Network/rust-sdk"
readme = "README.md"
license = "Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0-beta.12"
anyhow = "1.0.52"
async-recursion = "0.3.2"
async-stream = "0.3.2"
avro-rs = "0.13.0"
bytes = "1.1.0"
data-encoding = "2.3.2"
derive_builder = "0.10.2"
derive_more = "0.99.17"
futures = "0.3.19"
jsonwebkey = { version = "0.3.4", features = [ "pkcs-convert" ] }
lazy_static = "1.4.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
openssl = "0.10.38"
pipe = "0.4.0"
bigint = "4.4.3"
ring = "0.16.20"
serde = "1.0.132"
serde_json = "1.0.73"
sha2 = "0.10.0"
tokio = { version = "1.15.0", features = [ "fs" ]}
tokio-util = "0.6.9"
bs58 = "0.4.0"
ed25519-dalek = { version = "1.0.1", optional = true }
avro = "0.2.1"
reqwest = { version = "0.11.9", features = [ "json" ] }
thiserror = "1.0.30"

[dev-dependencies]
tokio-test = "0.4.2"

[features]
solana = ["ed25519-dalek"]
